site_name: Hammer Game Handbook
repo_url: https://github.com/mammoth-games/hammer

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

theme:
  name: material
  favicon: img/site/dude_small.png
  logo: img/site/hammer_small.png
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      accent: blue
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light blue
      accent: blue
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
    - pymdownx.highlight:
        linenums_style: pymdownx.inline
    - pymdownx.superfences
    - pymdownx.inlinehilite
    - pymdownx.keys
    - admonition